git_commit_id := $(shell git --git-dir $(LOCAL_PATH)/../../.git rev-parse --short HEAD)
git_commit_count := $(shell git --git-dir $(LOCAL_PATH)/../../.git rev-list HEAD --count)
git_local_branch := $(shell git --git-dir $(LOCAL_PATH)/../../.git symbolic-ref --short -q HEAD)
#date_string := $(shell date +%Y-%m-%d)
year := $(shell date +%Y)
month := $(shell date +%m)
day := $(shell date +%d)

$(info "-------------------------------------------------------------------")
$(info $(git_commit_id))
$(info $(git_commit_count))
$(info $(git_local_branch))
$(info $(year))
$(info $(month))
$(info $(day))
$(info "-------------------------------------------------------------------")
