#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# -*- encoding: utf-8 -*-
#
# Copyright (c) 2020 anqi.huang@outlook.com
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


import optparse
import os

VALUE_TYPE_INT = 0
VALUE_TYPE_BOOLEAN = 1
VALUE_TYPE_STRING = 2


class Generator:
    OUT_FILE_NAME = "BuildConfig.java"
    mOutConfDir = ''
    mOutConfPath = ''

    def __init__(self, outdir_root_dir):
        self.mOutConfDir = os.path.join(outdir_root_dir, "java/com/journeyOS/J007engine/")
        self.mOutConfPath = os.path.join(self.mOutConfDir, self.OUT_FILE_NAME)
        pass

    def generate(self, config_dict):
        if not os.path.exists(self.mOutConfDir):
            os.makedirs(self.mOutConfDir)

        with open(self.mOutConfPath, 'w+') as f:
            f.write("//This is auto generated by build_tools.py, don't modify.\n")
            f.write("package com.journeyOS.J007engine;\n\n")
            f.write("public class BuildConfig {\n\n")

            for k in config_dict:
                key = str(k)
                value = str(config_dict[key][0])
                type = config_dict[key][1]
                # print("key = %s , value = %s , value = %d" % (key, value, type))
                if type == VALUE_TYPE_INT:
                    f.write("    public static final int " + key + " = " + value + ";\n")
                    pass
                elif type == VALUE_TYPE_BOOLEAN:
                    f.write("    public static final boolean " + key + " = " + value + ";\n")
                    pass
                elif type == VALUE_TYPE_STRING:
                    f.write("    public static final String " + str(key) + " = " + "\"" + value + "\"" + ";\n")
                    pass

            f.write("\n}\n")
            f.close()


def parseargs():
    usage = "usage: %prog [options] arg1 arg2"
    parser = optparse.OptionParser(usage=usage)

    option_group = optparse.OptionGroup(parser, "auto gerrit review message options")

    option_group.add_option("-o", "--outdir", dest="outdir", default="", help="out dir")
    option_group.add_option("-c", "--version_code", dest="version_code", default="", help="build version code")
    option_group.add_option("-n", "--version_name", dest="version_name", default="", help="build version name")

    parser.add_option_group(option_group)

    (options, args) = parser.parse_args()

    return (options, args)


def main():
    (options, args) = parseargs()
    outdir = options.outdir.strip()
    version_code = options.version_code.strip()
    version_name = options.version_name.strip()
    features = {}
    features["BUILD_VERSION_CODE"] = (int(version_code), VALUE_TYPE_INT)
    features["BUILD_VERSION_NAME"] = (version_name, VALUE_TYPE_STRING)

    generator = Generator(outdir)
    generator.generate(features)

    return 0


if __name__ == "__main__":
    main()
